### ISSUE TITLE
Upgrade to Request-Promise 0.3.x

### ISSUE THREAD

**Issue by analog-nico** [andig/pimatic-volkszaehler#1]
Hi @andig long time no see ;)

Out of curiosity I checked your code to see if you are affected by braking changes. Actually you are.

The line in the middle:

``` coffee
    # httpGet returns a promise
    return (request options)
      .error (error) ->
```

... needs to be changed to:

``` coffee
    # httpGet returns a promise
    return (request options)
      .promise() # Added
      .error (error) ->
```

However, I wonder if the code works. According to the [Bluebird API](https://github.com/petkaantonov/bluebird/blob/master/API.md#error-rejectedhandler----promise) `.error` only catches operational errors. I think `.catch` would be more appropriate:

``` coffee
    # httpGet returns a promise
    return (request options)
      # Changed to .catch
      .catch (reason) ->
        # fail after maxRetries
        if (++retry > maxRetries)
          env.logger.warn "Failed " + options.uri + " - giving up"
          # Changed to reason.error since Request-Promise rejects with an object containing a lot
          throw reason.error
```

As you see in this snippet you don't need `.promise()` here. That is intentional. (**EDIT**: Removed .promise() which I accidentally copied and pasted.)

Anyway, if I misunderstood something and `.error` is the right way to go, you just need to add `.promise()` as shown above and that is all you need to do to upgrade to Request-Promise 0.3.1.

BTW, you find all details in the [migration instructions](https://github.com/tyabonil/request-promise#migrating-from-02x-to-03x).

Frohes Schaffen!
Nico

**Comment by andig** [comment]
@analog-nico thanks for getting back- excellent support, much appreciated!

I'll update my code and retest with 0.3.1. As for

> According to the Bluebird API .error only catches operational errors. 

You're right but bluebird seems to not handle this in utmost consequence: https://github.com/petkaantonov/bluebird/issues/352

I'll see if each error condition will be caught as before.

**Comment by analog-nico** [comment]
Oh, interesting. Every library should have its quirks. ;)

If you add the `.promise()` call as I have shown above you can continue to use `.error`. `.promise()` returns the original unaltered Bluebird promise. So it will work as you expect - Bluebird quirks included.

**Comment by andig** [comment]
Using 0.3.1 now and working as-is. Can we close this issue?

**Comment by analog-nico** [comment]
Of course. Have a good one!

**Comment by andig** [comment]
The please is on my side, thank you!
