### ISSUE TITLE
plugin has issues with v0.9 / config is not defined

### ISSUE THREAD

**Issue by leader21** [andig/pimatic-volkszaehler#5]
having no data in v0.9
![](http://www.youscreen.de/bokcaspnw65.jpg)

also it is not possible to change/save devices via the device manager
![](http://www.youscreen.de/ttfuopwxb45.jpg)

plugin version 0.2.0
pimatic version 0.9.26
my vz is relatively old, using v0.3. i did not dare to update since all is working actually until the pimatic release change now ;)

**Comment by sweebee** [comment]
@andig please release the latest changes to NPM

**Comment by leader21** [comment]
opened a thread on the forum https://forum.pimatic.org/topic/1917/volkszaehler-plugin-not-working
installed the plugin as sweebee advised.
values are ok now but saving / editing the device itself does not work as it throws up this error
![](http://www.youscreen.de/tpyzycvdh21.jpg)

![](http://www.youscreen.de/yvroszdhu45.jpg)

and debug warning :
warn [pimatic]: The device type Volkszaehler does not implement a destroy function

and seems that the values are not updated. having the same values since 20 minutes now.
after a reboot of pimatic the values are updated once then stay the same
next thing i discovered is that the variables do not appear in the variables menu.

**Comment by andig** [comment]
Just noticed that it wasn't published as th version number has not been incremented. Will push asap, please recheck with 0.2.1 then.

**Comment by andig** [comment]
published just now

**Comment by leader21** [comment]
Updated and checked but having the same issues. 
@andig are you able to reproduce my findings?

**Comment by mwittig** [comment]
@leader21 Despite the obvious error "assert.AssertionError is not a function" the duplicate UUID case pops up because the device class does not implement a destroy function with proper cleanup. Thus you should not use the device editor for now (use config editor instead). I'll try to come up with a PR to fix the issue.

**Comment by andig** [comment]
>  I'll try to come up with a PR to fix the issue.

Thanks @mwittig. Too many projects going on right now. If you do- could you make it a 0.3 version, please?

**Comment by leader21** [comment]
updated to 0.3 and all issues are gone (until now).
gonna have an eye on that...

**Comment by andig** [comment]
Excellent. Just noted that 0.9 has auto discovery as well- will try to add that for public channels, too.
